### PR TITLE
add support for ssl_name in regular reencrypt routes

### LINKED ISSUE #16: Proxy pass ssl_name needs to be adjusted for reencrypt use cases.
**Describe the bug**
custom ssl_name is needed for reencrypt. This is the case for integrated registry of openshift.

**Your environment**
* NGINX Router version 0.2
* Openshift version 3.11
* NGINX or NGINX Plus version 1.15

**Additional context**
i created some fixes in my fork, please review them if they are ready for a pull request.

**edit**
removed port section, as it is disscussed in #19 and fixed in pullrequest #21

### PR DESCRIPTION
**Pull request by Rikbruggink**
### Proposed changes
Fixes #16 and enables custom options for server and location parts of the config

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [/] I have read the [CONTRIBUTING](https://github.com/nginxinc/nginx-openshift-router/blob/master/CONTRIBUTING.md) guide
- [/] I have proven my fix is effective or that my feature works
- [/] I have updated necessary documentation
- [/] I have rebased my branch onto master
- [/] I will ensure my PR is targeting the master branch and pulling from my branch on my own fork

### CODE REVIEW

**Comment by pleshakov** [comment]
@Rikbruggink thanks for the PR!

Regarding `nginx.router.openshift.io/proxy_ssl_name` and `nginx.router.openshift.io/forward_port` annotation.
Could you possibly provide a Route resource that uses those annotations with keys redacted?

Regarding `nginx.router.openshift.io/server-snippets` and `nginx.router.openshift.io/location-snippets`.
Please note that those annotations can cause problems as the Router doesn't validate them. If any Router user uses one of those annotations with invalid NGINX config, the generated config becomes invalid and all the subsequent changes to the config (ex. new routes are added, endpoints are changed) will not be applied.
I wonder how you are planning to use those annotations. Maybe there is another way to address your requirements.

We will review the PR and get back to you soon.

**Comment by Rikbruggink** [comment]
The problem which occurs when you don't set the proxy_ssl_name is is that the host is used as ssl_name and from Openshift perspective the supplied cert uses the pod ip as CN. the port is need because the docker client otherwise redirects to the server port which is in the 10k range. Setting that to 443 corrects that.

> Regarding nginx.router.openshift.io/proxy_ssl_name and nginx.router.openshift.io/forward_port annotation.
Could you possibly provide a Route resource that uses those annotations with keys redacted?

```apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    nginx.router.openshift.io/proxy_ssl_name: '172.30.180.231'
    nginx.router.openshift.io/forward_port: '443'
  name: docker-registry
  namespace: default
spec:
  host: docker-registry-default.wildcard.default.domain
  tls:
    caCertificate: |
    < redacted >
    certificate: |
	< redacted >
    destinationCACertificate: |
    < redacted >
    key: |
	< redacted >
    termination: reencrypt
  to:
    kind: Service
    name: docker-registry
    weight: 100
  wildcardPolicy: None
```

>Regarding nginx.router.openshift.io/server-snippets and nginx.router.openshift.io/location-snippets.
Please note that those annotations can cause problems as the Router doesn't validate them. If any Router user uses one of those annotations with invalid NGINX config, the generated config becomes invalid and all the subsequent changes to the config (ex. new routes are added, endpoints are changed) will not be applied.
I wonder how you are planning to use those annotations. Maybe there is another way to address your requirements.
 
I understand that if the directives are used incorrectly the server config will not be applied to the running config. This is something that we want for our advanced users and use-cases. Perhaps some users want to sets the client body size to 8m. some other users wants it at 100m and we want it at 0 because of the registry. Or we want to set some setting that's not in the config yet. I would love to have all the annotations from the ingress controller also enabled here then most of our use-cases would be handled.

**Comment by pleshakov** [comment]
@Rikbruggink 
Thanks for the additional details.

> I understand that if the directives are used incorrectly the server config will not be applied to the running config.

It makes sense to have snippets annotations. However, because all other annotations are validated by the Router (meaning the Router will generate valid NGINX config), I think it is better to mark the snippets annotations as "unsafe".  Could you take a look at this proposal  https://github.com/nginxinc/nginx-openshift-router/issues/20 and see if it makes sense?

The `proxy_ssl_name` annotation makes sense. However, we have recently discovered a related bug: the for certificate validation, the Router sets the value of the `proxy_ssl_name` to the host of a Route, rather than the fully qualified name of the service in the Route, which is what the default Router does. In your example, if you use the fully qualified name of the docker-registry service as the value of the `nginx.router.openshift.io/proxy_ssl_name` annotation, will it solve the validation problem?
Also, if this annotation is not validated,  I would rather mark it as "unsafe" similar to the snippets annotations.

The forward port problem can be fixed differently without the `nginx.router.openshift.io/forward_port` annotation. The problem was also recently reported in https://github.com/nginxinc/nginx-openshift-router/issues/19. To fix the problem we can use the value of the `$httpsPort` template variable. This should solve the problem. If you are interested in contributing a fix for this problem, could you submit a fix in a separate PR?

**Comment by Rikbruggink** [comment]
@pleshakov #20 makes sense let's continue our discussion around that feature set there, i will exclude that portion from this PR.

> In your example, if you use the fully qualified name of the docker-registry service as the value of the nginx.router.openshift.io/proxy_ssl_name annotation, will it solve the validation problem?

No not in this case, Openshift used the ClusterIP as CN instead of the service name, so for us that won't be the solution. 

> Also, if this annotation is not validated, I would rather mark it as "unsafe" similar to the snippets annotations.

I don't know if we should guard this feature behind the same gate as the snippets. I can imagine that someone would like to enable this but not the snippets. The directive is also used in the TCP/UDP load balancing, this change would also affect existing users then.

> If you are interested in contributing a fix for this problem, could you submit a fix in a separate PR?

I also use the https port in that directive. I will also leave that part out of this PR and contribute the fix in a separate PR with the identifier that it fixes #19 when i tested that internally.

**Comment by pleshakov** [comment]
@Rikbruggink 
> I don't know if we should guard this feature behind the same gate as the snippets. I can imagine that someone would like to enable this but not the snippets. The directive is also used in the TCP/UDP load balancing, this change would also affect existing users then.

ok. agreed.

Found a small issue:
```
grpc_ssl_name {{ $ssl_name }}
. . .
proxy_ssl_name {{ $ssl_name }}
```
Since both lines do not end with `;`, this requires adding `;` as part of the annotation (example, `"nginx.router.openshift.io/proxy_ssl_name": "myapp.example.com;"`), which is inconsistent with the implemenation for the tcp Routes - see https://github.com/nginxinc/nginx-openshift-router/blob/99f96cd2fe7d16232ff11f3dc54c5c0e7f33ee51/src/nginx/conf/nginx-config.template#L488. Could you possible finish both lines with `;`?

Additionally, if you could move ` fixes #16` into the third line of the commit message, that'd be great! 

Thanks

**Comment by Rikbruggink** [comment]
@pleshakov My bad! the ; must have slipped through the rebase.. adjusted as requested.

**Review by pleshakov — APPROVED** [review]
👍

**Review by Rulox — APPROVED** [review]

**Comment by pleshakov** [comment]
@Rikbruggink thanks for the changes! could you possibly rebase against the master?

**Comment by Rikbruggink** [comment]
@pleshakov rebased against master.

**Comment by pleshakov** [comment]
@Rikbruggink thanks!

**Pull request merged**
