### PR TITLE
Fix the value of X-Forwarded-Proto header

### LINKED ISSUE #19: HTTP_X_FORWARDED_PORT incorrect on Passthrough routes
**Describe the bug**
The variable HTTP_X_FORWARDED_PORT=10444 pased to backend contaniners when we use passthrough routes when it must be 80 or 443.

**To reproduce**
1. Create route.
2. Show variables in backend

**Expected behavior**
 HTTP_X_FORWARDED_PORT=80 or  HTTP_X_FORWARDED_PORT=443

**Your environment**
* NGINX Router 0.2
* Openshift 3.11
* NGINX 1.1.5.6

**Additional context**

### PR DESCRIPTION
**Pull request by Rikbruggink**
### Proposed changes
Fixes #19 

### Checklist

- [V] I have read the [CONTRIBUTING](https://github.com/nginxinc/nginx-openshift-router/blob/master/CONTRIBUTING.md) guide
- [V] I have proven my fix is effective or that my feature works
- [V] I have updated necessary documentation
- [V] I have rebased my branch onto master
- [V] I will ensure my PR is targeting the master branch and pulling from my branch on my own fork

### CODE REVIEW

**Review by pleshakov — CHANGES_REQUESTED** [review]
@Rikbruggink thx for the PR!!

during testing I discovered that if we use a route that supports both HTTP and HTTPS and if we send an HTTP request to the host of that route, the value of the `X-Forwarded-Port` will still be set to the value of HTTPs port, which is a bug.

To solve this I suggest using the following map (we can place it after  `map $http_upgrade $connection_upgrade`):
```
  map $https $forwarded_port {
    default $server_port;
    'on' {{ $httpsPort }};
  }
```
And then use the `$forwarded_port` for `X-Forwarded-Port`.

More about $https variable -- http://nginx.org/en/docs/http/ngx_http_core_module.html#var_https

If you could  also change the PR/commit title to "Fix the value of X-Forwarded-Proto header" (note, you can put `Fixes #19` on the 3d line of the commit message) , that'd be great

**Comment by Rikbruggink** [comment]
Hi @pleshakov 

Proposed changes added to the files. Missed that bug, we dont support http in our environment, so i missed that..

**Review by Rulox — APPROVED** [review]
👍

**Comment by pleshakov** [comment]
@Rikbruggink thanks for the change. Just a small fix required - since the $forwarded_port is an NGINX variable not a template variable, `{{ }}` are not required: `proxy_set_header X-Forwarded-Port $forwarded_port;`

**Comment by Rikbruggink** [comment]
@pleshakov  Thnx! I thought it was a go variable. Adjusted.

**Review by pleshakov — APPROVED** [review]
👍

**Pull request merged**
